# Generated by Django 4.1.2 on 2022-11-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('alucodigo', models.AutoField(primary_key=True, serialize=False)),
                ('alunome', models.CharField(blank=True, max_length=45, null=True)),
                ('alumatricula', models.CharField(blank=True, max_length=45, null=True)),
                ('aluemail', models.CharField(blank=True, max_length=45, null=True)),
                ('aluserie', models.CharField(blank=True, max_length=45, null=True)),
                ('alufaltas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alunos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('procodigo', models.AutoField(primary_key=True, serialize=False)),
                ('pronome', models.CharField(blank=True, max_length=45, null=True)),
                ('promatricula', models.CharField(blank=True, max_length=45, null=True)),
                ('promateria', models.CharField(blank=True, max_length=45, null=True)),
                ('proemail', models.CharField(blank=True, max_length=45, null=True)),
                ('profaltas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('turcodigo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'turmas',
                'managed': False,
            },
        ),
    ]
