# Generated by Django 4.1.1 on 2022-11-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0003_materias_delete_djangoadminlog_delete_djangosession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
    ]
