# Generated by Django 4.1.3 on 2022-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0006_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunosdaturma',
            fields=[
                ('adtcodigo', models.AutoField(primary_key=True, serialize=False)),
                ('adtalunome', models.CharField(blank=True, max_length=45, null=True)),
                ('adtturnome', models.CharField(blank=True, max_length=45, null=True)),
                ('adtpronome', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'alunosdaturma',
                'managed': False,
            },
        ),
    ]
